name: CMake on Ubuntu with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        c_compiler: [gcc]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install libcurl
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Create Translations directory
      run: mkdir -p $HOME/.config/etree/locales

    - name: Download translations
      run: curl -sSL -o $HOME/.config/etree/locales/en.json https://raw.githubusercontent.com/rompelhd/Etree/main/locales/en.json

    - name: Create etree.conf
      run: echo -e "#Etree Config\nlanguageCode=en" > $HOME/.config/etree/etree.conf

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ${{ steps.strings.outputs.build-output-dir }}/etree
